package com.aibuilder.model;

import lombok.Data;

import java.util.List;

/**
 * Represents structure data generated by AI
 */
@Data
public class StructureData {
    private String name;
    private String description;
    private Size size;
    private List<Block> blocks;

    @Data
    public static class Size {
        private int width;
        private int height;
        private int depth;
    }
    
    @Data
    public static class Block {
        private int x;
        private int y;
        private int z;
        private String material;
        private String data; // For block data like stairs direction, etc.

        public Block() {}

        public Block(int x, int y, int z, String material) {
            this.x = x;
            this.y = y;
            this.z = z;
            this.material = material;
        }

        public Block(int x, int y, int z, String material, String data) {
            this(x, y, z, material);
            this.data = data;
        }
    }
}
